### ISSUE TITLE
Classic only: ⍴(HttpCommand.Get'www.dyalog.com').Data returns 0

### ISSUE THREAD

**Issue by dyaandys** [Dyalog/HttpCommand#35]
19.0.47901 classic (tried WIndows and AIX)
      ]load HttpCommand
#.HttpCommand
      HttpCommand.Version
 HttpCommand  5.4.0  2023-09-06 
      ⍴(HttpCommand.Get'www.dyalog.com').Data
0

is fine with Unicode 

Was fine in 18.2 with 4.0.14 for example (and I think was ok in versions of HttpCommand shipped with earlier 19.0s

**Comment by bpbecker** [comment]
This version of HttpCommand  (5.x) returns a 92 (Translation Error) return code because the Dyalog.com home page contains a vertical tab character (⎕UCS 11) and that's not in Classic's ⎕AVU.  Previous versions of HttpCommand would replace any such offending characters with '?'.  Nevertheless, HttpCommand should have returned the raw bytes in Data.
